import React, { useEffect, useState } from 'react';
import { LineChart, Line, BarChart, Bar, ResponsiveContainer, XAxis, YAxis, Tooltip } from 'recharts';
import { api } from '../services/api';
import ChartCard from '../components/ChartCard';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(n)||0);
export default function Analytics(){
 const [monthly,setMonthly]=useState([]),[cat,setCat]=useState([]),[reg,setReg]=useState([]),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api.monthly({}),api.categories({}),api.regions({})]).then(([m,c,r])=>{setMonthly(m);setCat(c);setReg(r)}).catch(e=>setError(e.message))},[]);
 const topCat=cat[0], topReg=reg[0];
 return <div className="page-content"><div className="page-intro"><div><h2>Analytics</h2><p>Explore trends and business performance from the connected database.</p></div></div>{error&&<div className="error-box">{error}</div>}<div className="two-col"><ChartCard title="Revenue Trend" subtitle="Monthly revenue"><ResponsiveContainer width="100%" height={300}><LineChart data={monthly}><XAxis dataKey="month" tickFormatter={m=>m.slice(5)} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}k`} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)}/><Line type="monotone" dataKey="revenue" stroke="#6d4aff" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Profit Trend" subtitle="Monthly profit"><ResponsiveContainer width="100%" height={300}><LineChart data={monthly}><XAxis dataKey="month" tickFormatter={m=>m.slice(5)} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}k`} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)}/><Line type="monotone" dataKey="profit" stroke="#f27a8a" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard></div><div className="two-col"><ChartCard title="Category Comparison"><ResponsiveContainer width="100%" height={300}><BarChart data={cat}><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}k`} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="revenue" fill="#6d4aff" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Regional Comparison"><ResponsiveContainer width="100%" height={300}><BarChart data={reg}><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}k`} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="revenue" fill="#f27a8a" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div><section className="card insights"><h3>Key Insights</h3><div className="insight-grid"><div><span>Top category</span><strong>{topCat?.name || '—'}</strong><p>{topCat ? money(topCat.revenue) : 'No data'}</p></div><div><span>Strongest region</span><strong>{topReg?.name || '—'}</strong><p>{topReg ? money(topReg.revenue) : 'No data'}</p></div><div><span>Highest monthly revenue</span><strong>{monthly.reduce((a,b)=>Number(b.revenue)>Number(a?.revenue||0)?b:a,null)?.month || '—'}</strong><p>{money(monthly.reduce((a,b)=>Number(b.revenue)>Number(a?.revenue||0)?b:a,null)?.revenue)}</p></div></div></section></div>;
}
